# http://travis-ci.org/#!/RDFLib/rdflib-jsonld
language: python
# whitelist
branches:
  only:
    - master
python:
    - 3.6
    - 3.7
    - 3.8
    - 3.9
    - pypy
    - pypy3

arch:
    - amd64
    - ppc64le

install:
    - pip install . nose flake8

before_script:
    - flake8 --exit-zero rdflib_jsonld

script:
    - nosetests

matrix:
  allow_failures:
    - python: pypy3
  exclude:
    - arch: ppc64le
      python: pypy
    - arch: ppc64le
      python: pypy3
