BASE = u'@base'
CONTAINER = u'@container'
CONTEXT = u'@context'
#DIRECTION = u'@direction'
GRAPH = u'@graph'
ID = u'@id'
#IMPORT = u'@import'
#INCLUDED = u'@included'
INDEX = u'@index'
JSON = u'@json'
LANG = LANGUAGE = u'@language'
LIST = u'@list'
NEST = u'@nest'
NONE = u'@none'
PREFIX = u'@prefix'
PROPAGATE = u'@propagate'
#PROTECTED = u'@protected'
REV = REVERSE = u'@reverse'
SET = u'@set'
TYPE = u'@type'
VALUE = u'@value'
VERSION = u'@version'
VOCAB = u'@vocab'
